
// This file is generated by a python parser, because I don't know how to read a config file during utools runtime.
// Date 2023-09-25 21:46:01
    

const macos = require('./data/json/macos.js')
const windows = require('./data/json/windows.js')
const magnet_macos = require('./data/json/magnet_macos.js')
const tmux = require('./data/json/tmux.js')
const vim = require('./data/json/vim.js')

updatePlaceHolder = (val) => {
    let newVal = val
    if (val.includes('{cmd_or_ctrl}')) {
        if (utools.isMacOs()) {
            newVal = val.replace(/{cmd_or_ctrl}/g, 'command')
        }
        else if (utools.isWindows()) {
            newVal = val.replace(/{cmd_or_ctrl}/g, 'ctrl')
        }
    }
    val = newVal
    if (val.includes('{opt_or_alt}')) {
        if (utools.isMacOs()) {
            newVal = val.replace(/{opt_or_alt}/g, 'option')
        }
        else if (utools.isWindows()) {
            newVal = val.replace(/{opt_or_alt}/g, 'alt')
        }
    }
    return newVal
}

function handleArr(arr) {
    for (let i = 0; i < arr.length; i++) {
        if (Array.isArray(arr[i])) {
            handleArr(arr[i]);
        } else {
            let val = arr[i]
            arr[i] = updatePlaceHolder(val)
        }
    }
}

handleTemplate = (arr) => {
    arr.forEach(x => {
        for (key in x) {
            if (Array.isArray(x[key])) {
                handleArr(x[key])
            }
            else {
                x[key] = updatePlaceHolder(x[key])
            }
        }
    })
}

const APP_ID_ALIASES = {
    'jet_brains': 'intellij-idea'
};

const fs = require('fs');
const path = require('path');

function loadAllShortcuts() {
    let shortcuts = [];
    const downloadedSet = new Set();
    
    // 步骤 2: 优先查阅 DB 内已下载的快捷方式
    try {
        const dbDocs = utools.db.allDocs('hotkeys_app_');
        console.log(`[ShortcutsLoader] Found ${dbDocs.length} custom docs using prefix 'hotkeys_app_'`);
        for (const rawDoc of dbDocs) {
            // Log a sample of the document to see its structure
            console.log(`[ShortcutsLoader] Processing doc: ${rawDoc._id || rawDoc.id || 'no-id'}`);
            
            // Try to find shortcuts in common formats
            const doc = rawDoc.doc || rawDoc.value || rawDoc;
            const appId = doc.appId || (doc._id ? doc._id.replace('hotkeys_app_', '') : 'unknown');
            const data = doc.shortcuts || doc.data || [];
            
            if (Array.isArray(data) && data.length > 0) {
                console.log(`[ShortcutsLoader] Successfully loaded ${data.length} shortcuts for ${appId}`);
                downloadedSet.add(appId);
                shortcuts = shortcuts.concat(data);
            } else {
                console.warn(`[ShortcutsLoader] Doc ${appId} has no shortcuts array`, doc);
            }
        }
    } catch (e) {
        console.error('[ShortcutsLoader] Failed to load DB shortcuts', e);
    }
    
    let shortcutTable = {
        macos: macos,
        windows: windows,
        magnet_macos: magnet_macos,
        tmux: tmux,
        vim: vim
    };

    let loaded = [];
    function requireAll(directory) {
        if (!fs.existsSync(directory)) return;
        const files = fs.readdirSync(directory);
        for(let file of files) {
            const filePath = path.join(directory, file);
            const stat = fs.statSync(filePath);

            if (stat.isDirectory()) {
                requireAll(filePath);
            } else if (path.basename(file) === 'shortcuts.js') {
                const sc = require(filePath);
                loaded = loaded.concat(sc);
            }
        }
    }

    requireAll(path.join(__dirname, 'data/shortcuts'));
    
    for(let k of loaded) {
        const name = k.name();
        
        // 步骤 3: 避免与静态配置项相碰撞（拦截过滤）
        const aliasId = APP_ID_ALIASES[name] || name;
        if (downloadedSet.has(aliasId)) {
            continue;
        }
        
        var sc = k.get();
        if (sc.length !== 0) {
            shortcutTable[name] = sc;
        }
    }

    for (let k in shortcutTable) {
        // template processing and platform filtering
        if (k.includes('template')) {
            if (!utools.isMacOs() && !utools.isWindows()) {
                continue;
            }
            handleTemplate(shortcutTable[k]);
        }
        else {
            if (utools.isMacOs()) {
                if (k.includes('windows')) {
                    continue;
                }
            }
            else if (utools.isWindows()) {
                if (k.includes('macos')) {
                    continue;
                }
            }
        }
        shortcuts = shortcuts.concat(shortcutTable[k]);
    }
    
    console.log(`[ShortcutsLoader] Total shortcuts loaded: ${shortcuts.length}`);
    return shortcuts;
}

module.exports = loadAllShortcuts;