
// This file is generated by a python parser, because I don't know how to read a config file during utools runtime.
// Date 2023-09-25 20:24:24
    

const welink_windows = require('./json/welink_windows.js')
const vscode_macos = require('./json/vscode_macos.js')
const macos = require('./json/macos.js')
const obsidian_windows = require('./json/obsidian_windows.js')
const vscode_windows = require('./json/vscode_windows.js')
const windows = require('./json/windows.js')
const obsidian_macos = require('./json/obsidian_macos.js')

let shortcutTable = {
    welink_windows: welink_windows,
    vscode_macos: vscode_macos,
    macos: macos,
    obsidian_windows: obsidian_windows,
    vscode_windows: vscode_windows,
    windows: windows,
    obsidian_macos: obsidian_macos,
}

let shortcuts = []
for (k in shortcutTable) {
    if (utools.isMacOs()) {
        if (k.includes('windows')) {
            continue
        }
    }
    else {
        if (k.includes('macos')) {
            continue
        }
    }
    shortcuts = shortcuts.concat(shortcutTable[k])
}
module.exports = shortcuts