import os
import argparse


def get_js_list(folder):
    out_files = []
    # 遍历目录
    for root, dirs, files in os.walk(folder):
        # 遍历文件
        for file_name in files:
            file_path = os.path.join(root, file_name)
            out_files.append(file_path)
    return out_files


def generate_js_code(file_list):
    import datetime

    # 获取当前日期和时间
    now = datetime.datetime.now()

    # 格式化日期和时间为字符串
    formatted_time = now.strftime("%Y-%m-%d %H:%M:%S")

    comment_head = '''
// This file is generated by a python parser, because I don't know how to read a config file during utools runtime.
// Shy😓
// Date {}
    '''.format(formatted_time)
    cat_line = ""
    code_lines = []
    export_line = ""
    for f in file_list:
        filename, ext = os.path.splitext(os.path.basename(f))
        var_name = filename
        if f.startswith("../"):
            f = f.replace("../", "./")
        code_lines.append("const {} = require('{}')".format(var_name, f))
        if cat_line == "":
            cat_line = var_name
            export_line = "module.exports = {}".format(var_name)
        else:
            cat_line = "{}.concat({})\n    ".format(cat_line, var_name)
    code_text = "\n".join(code_lines)
    code_text = "{}\n{}\n\n{}\n{}\n".format(comment_head, code_text, cat_line, export_line)
    return code_text


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-d', '--dir', type=str, help='输入js文件路径')
    parser.add_argument('-f', '--file', type=str, help='输出目标文件，不输入，则在本地输出shortcuts.js')
    args = parser.parse_args()

    folder_path = args.dir if args.dir is not None else "./json"
    output_file = args.file if args.file is not None else "./shortcuts.js"

    file_list = get_js_list(folder_path)
    text = generate_js_code(file_list)
    with open(output_file, 'w') as of:
        of.write(text)

    print("everything awesome😄")
